### ISSUE TITLE
dnSpy does not render icon fully

### ISSUE THREAD

**Issue by greenozon** [0xd4d/dnSpy#1462] opened 2020-05-10 07:21 UTC
- What version did you use?
dnSpy v6.1.4 (.NET Framework)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
navigate to resources section and browse the icon

I see it as follows (not fully rendered)

![image](https://user-images.githubusercontent.com/765343/81493300-e527b580-92a7-11ea-946e-d90d47244cc1.png)

assembly under review

[WindowsFormsApp2.zip](https://github.com/0xd4d/dnSpy/files/4605282/WindowsFormsApp2.zip)

**Comment by 0xd4d** [comment] 2020-05-10 12:08
I can't reproduce this, I tried .NET Core and .NET Framework, 64-bit and 32-bit. Try the .NET Core version and see if it works. Also if you haven't updated it yet, use the latest .NET Framework (4.8) with all fixes and OS fixes.

**Comment by greenozon** [comment] 2020-05-10 12:25
OK, looks like this is some specific env or .net issue
I'm using w7 with .net 4.8 and in my case I see corrupted (not fully drawn) icon
but  if you say it's fully rendered on your system then I guess it has nohting to do with dnSpy..

**Comment by 0xd4d** [comment] 2020-05-10 17:07
Did you try the .NET Core version?

**Comment by greenozon** [comment] 2020-05-10 17:46
Yes,
just gave it a try - same issue on mine PC

![image](https://user-images.githubusercontent.com/765343/81506481-4c248900-92ff-11ea-8cb2-cf455d1ca9d5.png)

My guess is that I dont have some patch... (for OS or for .NET)

**Comment by 0xd4d** [comment] 2020-05-11 19:17
I can reproduce it on Windows 7, but not on Windows 10.

**Comment by greenozon** [comment] 2020-05-11 19:28
Great! at least we have a common ground now :)
Thank you for the efforts

**Comment by 0xd4d** [comment] 2020-05-11 20:44
Win7 is EOL so I won't investigate why it can't load the image. It's a big icon file, it's possible that Win7 only supports smaller icon files.

**Comment by 0xd4d** [comment] 2020-07-23 19:41
Seems like an OS issue, so closing this.

**Closed by 0xd4d** 2020-07-23 19:41 UTC
