### ISSUE TITLE
Too many compile errors in DnSpy 6.1.5 (says that some files are missing) DnSpy v4.0.3 doesn´t have these errors, but it doesn´t show all the game files, like v6.1.5.

### ISSUE THREAD

**Issue by Userrr123** [0xd4d/dnSpy#1504] opened 2020-07-05 12:38 UTC
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by 0xd4d** [comment] 2020-07-05 21:12
Dupe of https://github.com/0xd4d/dnSpy/issues/1505

**Closed by 0xd4d** 2020-07-05 21:12 UTC
