### ISSUE TITLE
[Glitch] Decompiler calls constructor as a Method [ Base..Ctor() ]

### ISSUE THREAD

**Issue by LawnMower69** [0xd4d/dnSpy#1470] opened 2020-05-16 18:42 UTC
### **- What version did you use?**
6.1.4
### **- Write down all steps needed to reproduce this issue. Also attach any needed files.**

Decompile a .Dll

---

So basically DnSpy has a bug where it does not show you the **Constructor** in the beginning of the field but instead calls it as a **method**, 

It is not used that way in C#, and does not compile (I bet u already know that, right?)
If u didn't already, then I taught you, say thank you.

Which causes several things;

1. When you edit a value, once you decompile, you cannot recompile

2. when you remove the .ctor (to be able to compile), it removes the value:
(eg:) this.repairHealth = 10000f;
now compile, it turns into:
(eg:) this.repairHealth;

3. Even when you somehow go around that
Decompile ----> remove .ctor ----> compile ----> decompile ----> edit value ----> compile

(which is extremely broken in case you haven't noticed)

It breaks the file, and makes it as if **the entire class** (in which the edited Method was in), is now useless,
this has been attempted several times with different fields.

**_This means that you can no longer decompile with DnSpy_** (at least in my case)

![Alt text](https://i.imgur.com/fWurRT2.png)
![Alt text](https://i.imgur.com/czBnUN5.png)
![Alt text](https://i.imgur.com/Mfq40Ob.png)
![Alt text](https://i.imgur.com/lSNtUcB.png)

### **- Don't believe me?**
Try Editing literally Anything in Ravenfield 
(example used:
AssembelyCSharp --> wrench)

**Comment by LawnMower69** [comment] 2020-05-16 18:43
I hope this gets pushed in the next update:

Closed #1470 :3

FUCK YOU

**Comment by Kr4ken-9** [comment] 2020-05-16 21:39
This seems like a duplicate of https://github.com/0xd4d/dnSpy/issues/966
If you look at the CIL you will find that it is actually calling the base constructor so that part isn't unexpected. Here is an example from a similar Unity game:

![](https://i.imgur.com/rpwCa8f.png)

Notice that the base constructor is called after assigning `PlayerEquipment.slot` a value.
As you noticed you can workaround the base.cctor call just by removing it, resulting in this CIL:

![](https://i.imgur.com/itsrQVF.png)

Only difference is that now the base constructor is called before assigning `PlayerEquipment.slot`.

So now I am wondering what your problem is. Does MeleeWeapon require repairHealth to be assigned? In that case you can change the value of it by editing the CIL operand which will preserve the order of the CIL instructions. Example below:

![](https://i.imgur.com/KTwNwOF.png)

You can see I have changed the operand from previously `0xFF` to `0x100` while still calling the base constructor afterwards.

![](https://i.imgur.com/FWHI6Sq.png)

**Comment by LawnMower69** [comment] 2020-05-16 22:24
DnSpy just needs an update,

The only way to do the aforementioned is the extremely broken:
Decompile ----> remove .ctor ----> compile ----> decompile ----> edit value ----> compile

(which is extremely broken in case you haven't noticed)

which is bad, we just need it fixed.

**Comment by Kr4ken-9** [comment] 2020-05-16 22:30
I am not sure how you managed to create such a complicated process for editing the value. In the "aforementioned" you simply right click -> Edit IL -> Change operand -> Compile

CIL order is preserved, value is changed, compiles successfully. I agree it could be improved, but the process for changing a value is certainly not that convoluted.

**Comment by LawnMower69** [comment] 2020-05-16 22:39
read the fucking post

you're not here to magically solve people's problem with you shitty mouth

Shut up

**Comment by Trojaner** [comment] 2020-05-16 23:25
Someone ban this guy from the issue tracker already please

**Comment by 0xd4d** [comment] 2020-05-16 23:56
This has been answered, and the asshole has been blocked.

**Closed by 0xd4d** 2020-05-16 23:56 UTC
