### ISSUE TITLE
can't set breakpoint inside Action 

### ISSUE THREAD

**Issue by fuxuejun** [0xd4d/dnSpy#280] opened 2016-11-14 12:26 UTC
I can't set breakpoint inside the Action scope?

**Comment by SlowLogicBoy** [comment] 2016-11-14 13:06
If I understand correctly, you want to debug lambda expression, when lambda is compiled, compiler generates class and method for that lambda, so to debug that you need to enable:
![image](https://cloud.githubusercontent.com/assets/3121637/20265816/cbb9042c-aa7b-11e6-9530-930aa6e847d9.png)

**Comment by fuxuejun** [comment] 2016-11-14 14:20
sorry about the bad network in china. I want debug the code like
`
obj.MessageReceived = data =>{
    Console.WriteLine(data.Length);
}
`
I want set the breakpoint at Console.WriteLine().  But the breakpoint is auto set in the first line of the method.
I use the dnspy 3.0.
When I disable **Decompile anoymous methods/lambdas**, I can set the breakpoint into the auto generated method.

**Comment by 0xd4d** [comment] 2016-11-14 15:50
Seems like it's a dupe of #127

**Closed** 2016-11-18 06:02 UTC
Labels: question
