### ISSUE TITLE
Generated codes causing compilation errors

### ISSUE THREAD

**Issue by m1m2m3mr** [0xd4d/dnSpy#842] opened 2018-05-09 08:05 UTC
I'm trying to modify code with basic obfuscated codes but generated codes prevent dnSpy from compiling. I must remove all generated codes every time I made the change to the code in order to compile. Sometimes I meet a clean assembly with 2 or 4 lines of generated code with invalid syntax but removing them also works.

I'm using latest build 5.0.3 x.x.770

Here is the zip file: [Managed.zip](https://github.com/0xd4d/dnSpy/files/1986884/Managed.zip)

And here is the screenshot
![image](https://user-images.githubusercontent.com/20967118/39802943-c23feb92-536f-11e8-9f19-3d0d15ab6c67.png)

Here is another one
![image](https://user-images.githubusercontent.com/20967118/39867672-4d0cc7d6-5456-11e8-8c7a-4a14790f4759.png)

**Comment by 0xd4d** [comment] 2018-05-10 13:54
The first picture shows an obfuscated assembly. Use de4dot to rename the fields and methods.

The 2nd one is a dupe of #694

**Closed by 0xd4d** 2018-05-10 13:54 UTC

**Comment by m1m2m3mr** [comment] 2018-05-17 07:08
Ok i'll try it
