### ISSUE TITLE
dnspy will not open

### ISSUE THREAD

**Issue by K1TTY-K4T** [0xd4d/dnSpy#1494] opened 2020-06-28 18:11 UTC
have not changed anything and dnspy was working a few days ago.

**Comment by philipbawn** [comment] 2020-06-29 05:47
I have the same problem and fireeye at my organization seems to be detecting and deleting dnSpy.dll. Do you have that also?

Someone else with the same problem issue #1493

**Comment by 0xd4d** [comment] 2020-06-29 18:20
Duplicate of https://github.com/0xd4d/dnSpy/issues/1493

**Closed by 0xd4d** 2020-06-29 18:20 UTC
