### ISSUE TITLE
dnSpy.exe doesn't open.Nothing happens,I've downloaded everything it said to and I've even ran it as an admin. I've used the latest version too.

### ISSUE THREAD

**Issue by Harbinger-of-doom** [0xd4d/dnSpy#1503] opened 2020-07-05 04:21 UTC
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by 0xd4d** [comment] 2020-07-05 09:03
Dupe of https://github.com/0xd4d/dnSpy/issues/1493

**Closed by 0xd4d** 2020-07-05 09:03 UTC
