### ISSUE TITLE
Why is .editorconfig unuseful when git the source?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#593] opened 2017-11-02 11:35 UTC
If I download dnSpy by "Clone or download"-"Download ZIP", when I write code, "{" will place in the same line.

If I clone "https://github.com/icsharpcode/ILSpy.git" by Visual Studio 2017, when I write code, "{" will place in the new line.

Why?

**Comment by 0xd4d** [comment] 2017-11-02 14:10
Dupe of  #578, and off topic.

**Comment by 0xd4d** [comment] 2017-11-02 14:10
VS has its own forum.

**Closed by 0xd4d** 2017-11-02 14:10 UTC
Labels: invalid
