### ISSUE TITLE
[Feature Request]Hotkeys configurations/settings for custom key binding!

### ISSUE THREAD

**Issue by GameHackerPM** [0xd4d/dnSpy#1076] opened 2019-02-10 11:17 UTC
We all like this feature, it's awesome, but the most annoying part for me and for some users I know is it shouldn't be "Click" to navigate, we need it to be "Ctrl + Click" to navigate much better so when I use my mouse and click on an object or a method, it doesn't navigate directly.. I used to press a lot on them and every time it navigate to the declaration. The most familiar is to "Ctrl + Click" to navigate!

Just a request! ^^ Thanks a lot.

**Comment by 0xd4d** [comment] 2019-02-10 15:28
I don't agree. Most people are used to whatever browsers do and it's a single click to follow the link and ctrl+click to open in a new tab.

**Comment by GameHackerPM** [comment] 2019-02-10 17:11
> I don't agree. Most people are used to whatever browsers do and it's single click to follow the link and ctrl+click to open in a new tab.

If it possible to put a hotkey configurations/settings would be really great. It's not hard, but takes time I believe! Thanks for your reply..

**Comment by SylwesterZarebski** [comment] 2019-05-27 10:13
This issue an extension (shortcut configuration) to #324.

**Comment by aesalazar** [comment] 2019-06-20 22:22
@0xd4d Would you consider a PR for this feature?  I would be willing to put in some time if you are accepting of outside input.  I would follow whatever pattern/style you prefer.

**Comment by 0xd4d** [comment] 2019-06-22 10:27
@aesalazar  What feature is it, he changed the title, right now this issue is a dupe of https://github.com/0xd4d/dnSpy/issues/243

**Comment by aesalazar** [comment] 2019-06-22 16:51
@0xd4d Yes,  I was referring to changing the Keyboard shortcuts.  I looked at some of the sample extensions in the repo.  Seems like an extension would have the access necessary to pull this off?  If so, I can try to build something if it is not already in the works.

**Comment by 0xd4d** [comment] 2019-06-22 19:56
An extension can't do it because the current code has special code to add the shortcut, see eg.

code: https://github.com/0xd4d/dnSpy/blob/master/Extensions/Examples/Example1.Extension/CodeCtxMenus.cs#L26

That code should be removed. The command itself in that method could be exported and then imported by some command manager class. Other code (see menu item command below) can then get that command by passing in the name/id of the command to the command manager. No WPF deps are needed here.

menu item command: https://github.com/0xd4d/dnSpy/blob/master/Extensions/Examples/Example1.Extension/CodeCtxMenus.cs#L42

It would get the command and then execute it in its methods.

When the keyboard shortcut is pressed, the exported command should get called (not the menu item command).

What do you think about that?

There are a lot of commands so this could take a while...

**Comment by 0xd4d** [comment] 2019-06-22 19:58
Closing as dupe of #243, but you can still comment in this issue.

**Closed by 0xd4d** 2019-06-22 19:58 UTC

**Comment by aesalazar** [comment] 2019-06-23 11:15
@0xd4d   I think I get the gist of it.  If I get what you are suggesting, the command manager would exist in dnSpy itself.  By default, it would load the current set of keys that are currently implemented.

Then, each command could be customized by having the manager pulling them in.  Would that part live in an extension?  Or are you thinking it also has to go in the main app?

However it is done, I assume there would need a new screen in Options that would provide the GUI.  It would load the default settings but allow selection of letters and number plus the modifiers (ctrl, shift, alt).  Then save the whole in in a separate settings file.

Is that what you are thinking?

**Comment by 0xd4d** [comment] 2019-06-23 15:43
Yes it would have to be in dnSpy and not an extension since it's something that would be used by all commands. It would get the default shortcut keys from the exported commands that it imports. Any settings file could override that later.

The dialog box code isn't needed in the PR unless you want to add it. Otherwise it can be added later.

**Comment by GameHackerPM** [comment] 2019-06-23 18:34
Sounds awesome! Awaiting for the upcoming edits.

**Comment by aesalazar** [comment] 2019-06-24 17:14
Got it.  Let me take a look and see what I can come up with.  It's an impressive code base and a lot to take in! 😀
