### ISSUE TITLE
Use new SDK csproj for decompiled assemblies

### ISSUE THREAD

**Issue by verdie-g** [0xd4d/dnSpy#1447] opened 2020-04-19 08:36 UTC
Same as https://github.com/0xd4d/dnSpy/issues/959 but for generated csproj.

When decompiling assemblies using `dnSpy.Console.exe` the generated csproj are using the old format. This is a pain if you version the file using git as the `ProjectGuid` always change and it creates a huge diff whenever you decompile the assembly again.

**Comment by 0xd4d** [comment] 2020-04-19 20:26
> Same as #959 but for generated csproj.

That's not the same issue. That issue is about dnSpy's own csproj files.

Duplicate of https://github.com/0xd4d/dnSpy/issues/1185

You should be able to set the project guid when decompiling it so you don't get random GUIDs in the output.

**Closed by 0xd4d** 2020-04-19 20:26 UTC
