### ISSUE TITLE
C# 8.0  vs2019 surport？？

### ISSUE THREAD

**Issue by handashuai** [0xd4d/dnSpy#1405] opened 2020-02-27 03:24 UTC
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use?

- Write down all steps needed to reproduce this issue. Also attach any needed files.

**Comment by 0xd4d** [comment] 2020-03-02 18:26
Duplicate of https://github.com/0xd4d/dnSpy/issues/1404

**Closed by 0xd4d** 2020-03-02 18:26 UTC
