### ISSUE TITLE
Problem with a certain assembly

### ISSUE THREAD

**Issue by Crumbler** [0xd4d/dnSpy#484] opened 2017-08-11 11:17 UTC
So I'm trying to recompile a certain method in a xna game. The project itself references assembly X(thats not the actual name). For some reason I cannot use it when editing methods. I cannot reference. Assembly X also doesn't have a publickeytoken. Could it be the cause of the issue? If so, how can I fix it?

**Comment by 0xd4d** [comment] 2017-08-12 03:28
Seems like a dupe of #481 and a few other issues.

**Comment by Crumbler** [comment] 2017-08-12 16:57
You don't seem to get the issue. I'm trying to reference the assembly "ReLogic" in my code by typing "using". But I can't for some reason. The assembly "ReLogic" is **already referenced** within the project.
![image](https://user-images.githubusercontent.com/25861574/29242518-9672b8c0-7f97-11e7-9f11-1b8c4b5415d6.png)  . Here are all the libraries in the project folder 
![image](https://user-images.githubusercontent.com/25861574/29242527-c510da4a-7f97-11e7-9b36-1359c3e3574c.png) . Yeah I know, I checked the ReLogic.Native library but it's empty. I don't know what to do.

**Comment by 0xd4d** [comment] 2017-08-13 00:34
You clearly don't have ReLogic.dll so find it, put it in the same folder and try again.

**Closed by 0xd4d** 2017-08-13 00:34 UTC
Labels: question

**Comment by Crumbler** [comment] 2017-08-13 18:00
I scanned my whole PC and only found ReLogic.Native.dll which is empty and useless. Yet this mysterious ReLogic.dll is **referenced within the project**. Not only that, but ReLogic.dll is actively **used in the code** and has to be referenced by typing "using" to recompile a lot of important methods
[Terraria.zip](https://github.com/0xd4d/dnSpy/files/1220638/Terraria.zip)
. I've attached the .exe and all the .dll files included with it to this message. Go ahead and try to recompile: Terraria->Main->DoUpdate_HandleChat()

**Comment by UlyssesWu** [comment] 2017-08-14 01:51
Well, it's actually a simple question...
I just have bought this game on Steam, and after inspecting the main assembly for 1 minute I found the ReLogic.dll (full name is `<GameName>.Libraries.ReLogic.ReLogic.dll`) located in **resources**. The game just extracts it from resources and load it when running. Closed.
