### ISSUE TITLE
aysnc method code decompile issue

### ISSUE THREAD

**Issue by chenfeiw** [0xd4d/dnSpy#227] opened 2016-09-23 08:08 UTC
I have an async method as:
```
        async Task IEventProcessor.CloseAsync(PartitionContext context, CloseReason reason)
        {
            Console.WriteLine("Processor Shutting Down. Partition '{0}', Reason: '{1}'.", context.Lease.PartitionId, reason);
            if (reason == CloseReason.Shutdown)
            {
                await context.CheckpointAsync();
            }
        }
```
when i use dnSpy decompile the code, I see:
```
[DebuggerStepThrough, AsyncStateMachine(typeof(SimpleEventProcessor.<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__1))]
Task IEventProcessor.CloseAsync(PartitionContext context, CloseReason reason)
{
	SimpleEventProcessor.<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__1 <Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__ = new SimpleEventProcessor.<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__1();
	<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__.<>4__this = this;
	<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__.context = context;
	<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__.reason = reason;
	<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__.<>t__builder = AsyncTaskMethodBuilder.Create();
	<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__.<>1__state = -1;
	AsyncTaskMethodBuilder <>t__builder = <Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__.<>t__builder;
	<>t__builder.Start<SimpleEventProcessor.<Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__1>(ref <Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__);
	return <Microsoft-ServiceBus-Messaging-IEventProcessor-CloseAsync>d__.<>t__builder.Task;
}
```
Is there any option to see the code in await style?

And seems debug the async method has some issue.

**Comment by 0xd4d** [comment] 2016-09-23 11:52
Dupe of #118 and #127

**Closed by 0xd4d** 2016-09-23 11:52 UTC
