### ISSUE TITLE
v6.0.5 (dnSpy-netcore-win64.zip) throws exception

### ISSUE THREAD

**Issue by chenyj796** [0xd4d/dnSpy#1305] opened 2019-11-02 04:41 UTC
Before clicking `Submit new issue`, try the latest build [![](https://github.com/0xd4d/dnSpy/workflows/GitHub%20CI/badge.svg)](https://github.com/0xd4d/dnSpy/actions)

- What version did you use? 
v6.0.5 (dnSpy-netcore-win64.zip)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
It thows an exception where ever I click. 
The dialog as below:
![image](https://user-images.githubusercontent.com/18184515/68066067-355c1300-fd6d-11e9-8b0f-47420f000a99.png)

**Comment by 0xd4d** [comment] 2019-11-02 14:53
Is it this issue https://github.com/dotnet/wpf/issues/1269 ?

**Comment by 0xd4d** [comment] 2019-11-08 11:50
Closing it as a dupe of the above WPF issue.

**Closed by 0xd4d** 2019-11-08 11:50 UTC
