### ISSUE TITLE
Invalid token '<' in class, struct or interface member declaration

### ISSUE THREAD

**Issue by Octolus** [0xd4d/dnSpy#828] opened 2018-04-25 15:50 UTC
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
v4.5.3 (x86)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
I edited a method, and clicked compile. I did not edit anything, and it throws this error: https://i.imgur.com/Vo4OlRO.png

Has happened alot of times with this project for some reason.. some methods work, some don't.. i believe its the class that has some problem

I am trying to debug a Unity game :)

**Comment by SlowLogicBoy** [comment] 2018-04-26 12:57
Try:
Options -> Decompiler -> Show hidden compiler generated types and members

**Comment by UlyssesWu** [comment] 2018-04-27 02:12
Try removing all members which contain `<` `>` in both `.cs` and `.g.cs` if those members are not used in your modified code. Otherwise rename those used members with valid names and then edit code.

**Comment by 0xd4d** [comment] 2018-04-27 08:29
Looks like a dupe of #694.

**Closed by 0xd4d** 2018-04-27 08:29 UTC
Labels: decompiler
