### ISSUE TITLE
feature request : Show value on hover  

### ISSUE THREAD

**Issue by rekna1** [0xd4d/dnSpy#1280] opened 2019-09-30 06:58 UTC
Is it possible to show values of properties and variables on hovering over  ?
Or rightclick/evaluate would also be sufficient if hover is to difficult...

Would be major time saver.

**Comment by 0xd4d** [comment] 2019-09-30 19:14
Duplicate of https://github.com/0xd4d/dnSpy/issues/46

**Closed by 0xd4d** 2019-09-30 19:14 UTC
