### ISSUE TITLE
Compiler errors when editting class with lambda methods

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#299] opened 2016-12-09 22:11 UTC
Have 2 methods, one of which uses a lambda.
When editting the C# code of the other method; the generated method for the lamda expression is inserted into the hidden part of the partial class, causing compiler errors.

The editor should remove the definition of lambda backing methods ```<MyMethod>m__###()``` from the partial class definition the editor users for compilation.

**Comment by maritaria** [comment] 2016-12-09 22:15
Maybe remove all definitions marked with CompilerGenerated ?

**Comment by 0xd4d** [comment] 2016-12-10 10:12
> Maybe remove all definitions marked with CompilerGenerated ?

It's not safe to remove all defs with CompilerGeneratedAttribute.

Do you have steps on how to reproduce this or a link to a file I could have a look at?

**Comment by maritaria** [comment] 2016-12-11 23:09
# Code
```using System;
using System.Collections.Generic;

namespace CompilerGeneratedEnhancement
{
    public class Class1
    {
        private List<string> _yieldReturnTestStorage = new List<string> { "1", "2", "3" };

        public Class1 MyProperty { get; set; }

        public event EventHandler MyEvent;

        public void EditThisMethod()
        {
            MyEvent += Class1_MyEvent;
            MyProperty = this;
        }

        private void Class1_MyEvent(object sender, EventArgs e)
        {
            throw new NotImplementedException();
        }

        public void MethodWithLambda()
        {
            _yieldReturnTestStorage.ForEach(s => Console.WriteLine(s));
        }

        public IEnumerable<string> YieldReturnTest()
        {
            foreach (string s in _yieldReturnTestStorage)
            {
                yield return s;
            }
        }

    }
}
```
# What to do:
1. Open *Class1.EditThisMethod*
1. Click on *Edit C#*
2. Click on *Compile*

# Things to be excluded:
1. Compiler generated lambda helper classes/methods should be removed
2. Compiler generated backing fields for properties should be removed
3. Compiler generated backing fields for events should be removed
4. **Anything that is not a valid regular/normal C# name** (such as  <>k__backingfield; or $_something)

In case 4; if it isnt valid then it won't compile anyway. You can add them as comments in cases where you arent sure what their purpose is.

**Comment by maritaria** [comment] 2016-12-11 23:14
Reproductive gist containing original code and the decompiled code presented by dnSpy:
https://gist.github.com/maritaria/1eac2fcd8ee697e39491f72b3b013ea3

**Comment by 0xd4d** [comment] 2016-12-12 05:04
I can't reproduce it.

Have you enabled `Show hidden compiler generated types and methods` in the settings?

**Comment by 0xd4d** [comment] 2016-12-12 05:56
See also #302

**Comment by maritaria** [comment] 2016-12-13 10:51
You are right; the option ```Show hidden compiler generated types and methods``` was adding the definitions to the code.
When unchecked I still had problems when using 'Edit Class(C#)...' as it doesnt seem to insert lambda's correctly and messes up the call to the base ctor. I checked and I do have ```Decompile anonymous methods/lambdas``` enabled.

main.cs when using 'Edit Class (C#)...':
```
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;

namespace CompilerGeneratedEnhancement
{
	// Token: 0x02000002 RID: 2
	public class Class1
	{
		// Token: 0x17000001 RID: 1
		// (get) Token: 0x06000001 RID: 1 RVA: 0x00002050 File Offset: 0x00000250
		// (set) Token: 0x06000002 RID: 2 RVA: 0x00002058 File Offset: 0x00000258
		public Class1 MyProperty
		{
			get;
			set;
		}

		// Token: 0x14000001 RID: 1
		// (add) Token: 0x06000003 RID: 3 RVA: 0x00002064 File Offset: 0x00000264
		// (remove) Token: 0x06000004 RID: 4 RVA: 0x0000209C File Offset: 0x0000029C
		[method: CompilerGenerated]
		[CompilerGenerated]
		public event EventHandler MyEvent;

		// Token: 0x06000005 RID: 5
		public void EditThisMethod()
		{
			Console.WriteLine("How to reproduce:");
			Console.WriteLine("1. Click on 'Edit C#'");
			Console.WriteLine("2. Click on 'Compile'");
			Console.WriteLine("Things that are wrong:");
			Console.WriteLine("1. Compiler generated lambda helper classes/methods should be removed");
			Console.WriteLine("2. Compiler generated backing fields for properties should be removed");
			Console.WriteLine("3. Compiler generated backing fields for events should be removed");
			this.MyEvent += new EventHandler(this.Class1_MyEvent);
			this.MyProperty = this;
		}

		public // Token: 0x06000006 RID: 6 RVA: 0x0000214A File Offset: 0x0000034A
		void Class1_MyEvent(object sender, EventArgs e)
		{
			throw new NotImplementedException();
		}

		// Token: 0x06000007 RID: 7 RVA: 0x00002152 File Offset: 0x00000352
		public void MethodWithLambda()
		{
			List<string> arg_26_0 = this._yieldReturnTestStorage;
			Action<string> arg_26_1;
			if ((arg_26_1 = <>c.<>9__10_0) == null)
			{
				arg_26_1 = (<>c.<>9__10_0 = new Action<string>(<>c.<>9.<MethodWithLambda>b__10_0));
			}
			arg_26_0.ForEach(arg_26_1);
		}

		// Token: 0x06000008 RID: 8 RVA: 0x00002180 File Offset: 0x00000380
		public IEnumerable<string> YieldReturnTest()
		{
			return new <YieldReturnTest>d__11(-2)
			{
				<>4__this = this
			};
		}

		// Token: 0x06000009 RID: 9 RVA: 0x00002190 File Offset: 0x00000390
		public Class1()
		{
			this._yieldReturnTestStorage = new List<string>
			{
				"1",
				"2",
				"3"
			};
			base..ctor();
		}

		public // Token: 0x04000001 RID: 1
		List<string> _yieldReturnTestStorage;
	}
}
```

**Comment by 0xd4d** [comment] 2016-12-13 11:48
It's because the decompiler doesn't fully support Roslyn, see #118 

It's always best to just edit one method at a time since decompiler bugs could prevent code from compiling.

**Comment by 0xd4d** [comment] 2016-12-14 14:02
Closing it, #118 tracks fixing Roslyn support.

**Closed by 0xd4d** 2016-12-14 14:02 UTC
Labels: enhancement
