### ISSUE TITLE
ELEVATION REQUIRED when debugging with UAC enabled

### ISSUE THREAD

**Issue by ViRb3** [0xd4d/dnSpy#34] opened 2015-09-18 02:16 UTC
Running dnSpy as Administrator and debugging an executable throws "ELEVATION REQUIRED" exception when the executable is started. 

I tried forcing Administrator mode for dnSpy and using a Verb of "runas" for the debugger as well, but it didn't work.

The only workaround solution so far is to find the file you want to debug, Right-click -> Properties -> Compatibly -> Always run as Administrator

**Comment by 0xd4d** [comment] 2015-09-18 18:43
I've been able to reproduce this when this was added to the debugged application's manifest file

```
<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
```

A quick google search seems to say that it's not possible to request admin rights at runtime, you must start a new process with admin rights.

Always forcing dnSpy to use admin rights is out of the question, so perhaps the only solution would be to show a message box to the user to restart dnSpy with admin rights.

**Comment by ViRb3** [comment] 2015-09-18 20:23
The problem I encountered was that even if I ran dnSpy as Administrator, it would still be unable to elevate the debugged process (thus the error). Even after forcing it to do so, it threw the same exception.

**Comment by 0xd4d** [comment] 2015-09-19 07:07
Do you have a test? I can't reproduce it.

**Comment by 0xd4d** [comment] 2015-09-25 20:56
Closed, can't reproduce.

**Comment by 0xd4d** [comment] 2015-09-27 10:22
Reopened, I can reproduce it with the file @ViRb3 sent me.

**Comment by ViRb3** [comment] 2015-10-01 23:33
Any clue on where the problem is? I can try to help analyzing and debugging tomorrow.

**Comment by Lailok3n** [comment] 2015-10-02 02:31
Can the file be posted? Or is it sensitive/copyrighted?

**Comment by 0xd4d** [comment] 2015-10-02 06:17
If you hex edit it and change requestedExecutionLevel's uiAccess from true to false, you are able to debug it. I'll see later if it's possible to do it without hex editing the file.

**Comment by 0xd4d** [comment] 2015-10-25 15:48
I'll close this. Either hex edit it or use the trick described in the first post.

**Closed by 0xd4d** 2015-10-25 15:48 UTC
