### ISSUE TITLE
InvalidOperationException on undo after 'Edit Class (C#)...'

### ISSUE THREAD

**Issue by maritaria** [0xd4d/dnSpy#305] opened 2016-12-13 10:46 UTC
[Code](https://gist.github.com/maritaria/1eac2fcd8ee697e39491f72b3b013ea3)

1. Edit Class1 using the 'Edit Class (C#)...' feature
2. Remove everything except the MyProperty definition
3. Compile (the class now only has MyProperty left)
4. Press Ctrl+Z

I got [this](http://prntscr.com/diu23a) exception box

**Comment by 0xd4d** [comment] 2016-12-13 11:44
I can't reproduce it. Could you show a pic of the decompiler settings?

**Comment by maritaria** [comment] 2016-12-14 08:19
Was able to reproduce using version 3.0.1 (x64)
![decompiler settings](http://image.prntscr.com/image/f3ccc607303a46bca881dc4e49cb1658.png)

Download assembly I used: [dnSpyTest.dll](https://github.com/0xd4d/dnSpy/files/651101/dnSpyTest.dll.txt)
Remove .txt extension from the downloaded file (github restricts uploading files named *.dll).

**Comment by 0xd4d** [comment] 2016-12-14 11:29
I still can't repro it. Have you tried the latest build?

**Comment by maritaria** [comment] 2016-12-14 11:54
Bug does not occur on latest build; I was using latest release before.

**Comment by 0xd4d** [comment] 2016-12-14 13:42
Should be fixed now, it only triggered in Release builds, that's why couldn't repro it earlier.

**Closed** 2016-12-14 13:41 UTC
Labels: bug
