### ISSUE TITLE
Error export to project

### ISSUE THREAD

**Issue by xuan2261** [0xd4d/dnSpy#1415] opened 2020-03-14 04:18 UTC
I use dnSpy 6.1.3 and i export to project. After export and open with visual studio, i can not open Form because error "The variable  'componentResourceManager' is either undeclared or was never assigned."  I try check Unpack resources but still get that error.You can help me fix it. Thansk you very much.
You can Enable option Create .resx files
I try export with ILSpy then that error does not appear, i can open project after export normal.

![image](https://user-images.githubusercontent.com/17797687/76674736-1e63e200-65e5-11ea-932e-0ebbbebbcb6a.png)

![loi dnSpy 1](https://user-images.githubusercontent.com/17797687/76674753-3cc9dd80-65e5-11ea-8697-abf435110648.PNG)

**Comment by 0xd4d** [comment] 2020-03-17 17:31
So the latest version of it fixes it. I'll close it as a dupe of see https://github.com/0xd4d/dnSpy/issues/936 .

**Closed by 0xd4d** 2020-03-17 17:31 UTC
