### ISSUE TITLE
dnSpy cannot read 'published as single' app

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1416] opened 2020-03-14 09:48 UTC
Dragging a .NET Core 3.1 app published as single file on dnSpy makes it appear as unreadable. While a Windows application at least shows the PE information, a Linux application shows nothing besides its name.

**Comment by 0xd4d** [comment] 2020-03-14 15:39
Duplicate of https://github.com/0xd4d/dnSpy/issues/1174

**Closed by 0xd4d** 2020-03-14 15:39 UTC
