### ISSUE TITLE
save code disabled in V5.x.xxx

### ISSUE THREAD

**Issue by gagmeng** [0xd4d/dnSpy#943] opened 2018-09-21 09:05 UTC
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
5.0.8
- Write down all steps needed to reproduce this issue. Also attach any needed files.
The save and save all function is disabled in dnspy 5.x.xxx，pls see the below snapshot.
[http://www.hostpic.org/images/1809211433310095.jpg](url)

**Comment by gagmeng** [comment] 2018-09-22 14:00
But the save and save all function works fine in dnspy 4.5.X.

**Comment by 0xd4d** [comment] 2018-09-24 10:54
Looks like a dupe of #946

**Closed by 0xd4d** 2018-09-24 10:54 UTC
Labels: not reproducible, question
