### ISSUE TITLE
When debugging in IL view, step over/into won't single step instead it will step based on the disassembled code

### ISSUE THREAD

**Issue by xsilent007** [0xd4d/dnSpy#1359] opened 2020-01-03 19:03 UTC
- What version did you use? v6.0.5

- Write down all steps needed to reproduce this issue. Also attach any needed files.

1. Open any file
2. Set decompiler to IL
3. Set a breakpoint somewhere
4. Start debugging
5. After the breakpoint hits, try to step into/over

**Comment by 0xd4d** [comment] 2020-01-04 00:30
Duplicate of https://github.com/0xd4d/dnSpy/issues/216

**Closed by 0xd4d** 2020-01-04 00:30 UTC
