### ISSUE TITLE
BUG: Do not support the "this" keyword!

### ISSUE THREAD

**Issue by softmgr** [0xd4d/dnSpy#695] opened 2018-01-15 00:35 UTC
The following code is compiled and passed in vs2013:

		private void Start()
		{
			AttackLogic.field = this;  //CS0029 error in dnspy
			//..........................
		}

After the program is compiled to exe by vs2013, the error CS0029 by dnspy decompile!

**Comment by 0xd4d** [comment] 2018-01-15 17:22
There's not enough information to reproduce it.

**Comment by softmgr** [comment] 2018-01-16 05:41
@0xd4d 
The above code is located:
#633 in CSharp.zip, after extracting files: CSharp.dll - > JyGame - > BattleField - > private void (Start)

**Comment by 0xd4d** [comment] 2018-01-16 08:27
Seems to be a dupe of #365

**Closed by 0xd4d** 2018-01-16 08:27 UTC
Labels: decompiler

**Comment by 0xd4d** [comment] 2018-02-12 17:10
This has now been fixed, get the latest build.
