### ISSUE TITLE
dnSpy should be more user-friendly.

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#630] opened 2017-11-24 16:41 UTC
Some useful functions have no shortcut or so long.
such as:
Reload all assembies : no
Go to Entry Point : no
Open Containing Folder : no
Analyze : Ctrl+Shift+R so long

Some less usefull functions have short shortcut:
such as:
Ctrl+R Ctrl+T Ctrl+E Ctrl+G in Seach

I think dnSpy should remove Ctrl+R for searching resource, and add a "global shortcut" for Analyze.

That's because:
I think most people only need 2-4 options in search(constant, type, member, other)
Even if he want to search Resource exactly, he can choice from ComboBox without shortcut.
Instead, the most useful search option "Number/String(Constant)" is hard to use,
because it is placed in the bottom and the left hand is hard to press its shortcut "Ctrl+L".
I think dnSpy should use this order:
Number/String
All of the Bellow
.....
Free all or some less useful shortcut in search option to global shortcut.

Then can assign Ctrl+R to Anlyze, and some other to useful functions.

**Comment by 0xd4d** [comment] 2017-11-24 18:17
Dupe of #243

**Closed by 0xd4d** 2017-11-24 18:17 UTC
Labels: duplicate
