### ISSUE TITLE
<>f__mg$ Symbol(s)

### ISSUE THREAD

**Issue by jarrodm08** [0xd4d/dnSpy#992] opened 2018-11-12 14:30 UTC
I am trying to decompile an APK (for educational purposes) so that I can understand the formula/math used in calculations within the game (as I really admire their complexity), I am trying to recompile a portion of the code (for debugging/testing purposes only) and one of the scripts contain "unexpected symbols" preventing me from compiling.

The Line (though there are multiple through the script) with the unexpected symbol reads:
`		[CompilerGenerated]
		private static LoadingscreentipHelper.MappingAction <>f__mg$cache0;`

I tried googling but have not been successful in finding much information on, what this is, why it occurs, and how to fix it to enable compiling properly.
I am still very new to coding, so i'm sorry in advanced if this seems like a self-explanatory question to more seasoned-developers.

[Here is the a pastebin of the script file.](https://pastebin.com/5b5Xmn6u)

Side note: I also used a secondary program that does extremely well in decompiling most if not everything from a compiled unity project, and the same script within their program can be 
[read here](https://pastebin.com/4aK5KstM) (PS: their is mention of dnSPY in this pastebin due to the program using dnSPY as its decmompiler for scripts)

Notice how the second program uses a different name than dnSPY does when decompiling, though still looks like something is not right. Can someone help explain this or at least help me make it compile-able?

- Version 5.x.x of dnSPY

- Links provided above to the files in question

EDIT: Following the odd-named items, I can trace tem back (usually) to being defined somewhere else in the same script, giving me an idea of what it is (a dictionary, int, ect), I just renamed them all to something like _cgDict or _cgInt, this seems to remove the errors but whether or not this will let me fully compile I am not sure, as I have to sort through hundreds of variables in this manner.

**Comment by 0xd4d** [comment] 2018-11-12 20:19
Closing this, it's a dupe of https://github.com/0xd4d/dnSpy/issues/694

**Closed by 0xd4d** 2018-11-12 20:19 UTC

**Comment by EliuFlorez** [comment] 2020-01-25 03:39
Same mistake over here.
version: 6.0.0.5559
```
[CompilerGenerated]
	private static Func<object, CloudCurrency> <>f__mg$cache0;
```

**Comment by EliuFlorez** [comment] 2020-01-25 03:45
Hi guys, what would be more or less the solution for this code.
```
public class CloudCurrencyResponse : CloudResponse
{
	public List<CloudCurrency> currencies = new List<CloudCurrency>();

	[CompilerGenerated]
	private static Func<object, CloudCurrency> <>f__mg$cache0;

	public override void parseResponse(WWW www)
	{
		base.parseResponse(www);
		if (responseData != null)
		{
			currencies = responseData[0].parseJsonObjList("currencies", CloudCurrency.buildFromJson);
		}
		else
		{
			currencies = new List<CloudCurrency>();
		}
	}
}
```
