### ISSUE TITLE
code editor failed to recognize pure interface and report missing type error

### ISSUE THREAD

**Issue by funkvps** [0xd4d/dnSpy#731] opened 2018-02-16 08:19 UTC
[STAP.zip](https://github.com/0xd4d/dnSpy/files/1730579/STAP.zip)

Hello sir,

Thanks for this good tool!. Recently, it seems I have faced a bug in the code editor. The code editor and compile feature will failed to recognize  some pure interface, and will report missing type error.

Please take attached dll for example, and goto STAP.Utility.APCaseHelper and click edit class, then click compile, you will fond that the program report the following error.

The type or namespace name 'HappLS' could not be found (are you missing a using directive or an assembly reference?)	main.cs	17

However, the referenced interface is already there.

Best Regards

**Comment by 0xd4d** [comment] 2018-02-16 08:35
Dupe of #388

**Closed by 0xd4d** 2018-02-16 08:35 UTC
Labels: duplicate

**Comment by 0xd4d** [comment] 2018-02-16 08:39
Should be issue #386
