### ISSUE TITLE
Ability to save the (renamed) names only and auto load them on restart

### ISSUE THREAD

**Issue by lyanidle** [0xd4d/dnSpy#557] opened 2017-10-17 06:53 UTC
The renamed class names/methods are lost right now upon restart (forced to save to a new binary where is not guaranteed that the new binary still works).

I hope there will be a feature that will allows to save all renamed names and reload/replace them after restart automatically.

Was a bad surprise after dnSpy froze/crashed and my whole progress was lost.

Overall though the best thing I had in my hands for .NET debugging really nice.

**Comment by 0xd4d** [comment] 2017-10-17 09:50
> Was a bad surprise after dnSpy froze/crashed and my whole progress was lost.

If you have more info on how to reproduce this, please open a new issue.

This feature request is a dupe of #266 so I'm closing it.

**Closed by 0xd4d** 2017-10-17 09:50 UTC
