### ISSUE TITLE
[Question] How to add Comments / Rename functions & Members without editing assembly?

### ISSUE THREAD

**Issue by HurricanKai** [0xd4d/dnSpy#934] opened 2018-09-10 21:56 UTC
i found #266 and found it fixed years ago, but i cant find the feature anywhere?
I love this software, but im really missing this, can someone explain to me how to add comments and rename stuff?

**Comment by SlowLogicBoy** [comment] 2018-09-11 05:51
Duplicate of #266

**Comment by 0xd4d** [comment] 2018-09-11 14:13
#266 hasn't been implemented yet since it's still open. So in other words, you can't do it at the moment.

**Comment by HurricanKai** [comment] 2018-09-17 07:12
Oh :sweat_smile: I didn't notice, sorry ^^

**Closed** 2018-09-17 07:13 UTC
Labels: question
