### ISSUE TITLE
enhance the "Search For" combobox

### ISSUE THREAD

**Issue by chenyj796** [0xd4d/dnSpy#906] opened 2018-08-08 05:52 UTC
Before clicking `Submit new issue`, try the [latest build](https://ci.appveyor.com/project/0xd4d/dnspy/branch/master/artifacts)

- What version did you use?
dnSpy v5.0.1

- Write down all steps needed to reproduce this issue. Also attach any needed files.
1) Press Ctrl+Shift+K
2) Show "Search For" combobox
the default option is "All of the above", but I just need "Class" at most time for less results.
expecting the options shown as tree nodes within checkbox, so I can select some options and save them as default setting.

**Comment by Symbai** [comment] 2018-08-08 07:43
Sounds interesting but in this case it makes more sense to make default settings for the overall search. For example I search mostly within the selected file only so it would be nice to have this combobox included as well. And so can the checkbox for searching in GAC too.

**Comment by 0xd4d** [comment] 2018-08-08 08:26
Seems like a dupe of https://github.com/0xd4d/dnSpy/issues/778

You probably don't want Class but Type. Class is for reference types only. To search for type, press Ctrl+T or use the combobox dropdown.

**Closed** 2018-10-06 06:54 UTC
Labels: feature-request
