### ISSUE TITLE
Immense memory leak and slow decompilation issue

### ISSUE THREAD

**Issue by ddf420** [0xd4d/dnSpy#1029] opened 2018-12-28 07:03 UTC
When I try to export terraria to project with dnspy 5.0.12 it took more than 10 minutes and used more than 6gb of RAM
maybe GC or decompilation engine issue?
https://imgur.com/a/FXctVp3

**Comment by 0xd4d** [comment] 2018-12-28 08:04
Sounds like https://github.com/0xd4d/dnSpy/issues/972

What happens when you drag and drop all required files to Assembly Explorer and then decompile? Make sure you test the latest build, not the latest v5.0.12.

**Comment by ddf420** [comment] 2018-12-28 15:57
yes I tried the latest build. But other modern decompilers have no major problem 
aside from the program has one of the largest code I think the ilspy decompiler have problem
tried disabled io mapping and used 32 bit (x86 took 17 min to export to project)
 binary: https://github.com/blushiemagic/tModLoader/releases/download/v0.10.1.5/tModLoader.Windows.v0.10.1.5.zip
I think you can repro this

**Comment by 0xd4d** [comment] 2018-12-28 16:10
Dupe of https://github.com/0xd4d/dnSpy/issues/811

**Closed by 0xd4d** 2018-12-28 16:10 UTC
Labels: decompiler
