### ISSUE TITLE
Cannot sort local variable columns from caption headers while debugging

### ISSUE THREAD

**Issue by eng-marani** [0xd4d/dnSpy#808] opened 2018-04-09 15:09 UTC
- What version did you use?
4.5.3

- Write down all steps needed to reproduce this issue. Also attach any needed files.
While debugging, it would be very useful to click headers on locals name to "SORT" them ascending/Descending/None. I know there is an option flag, but standard caption sorting would be better.

Also, i really miss an "Inspect value" popup when hovering over a local while debugging.

**Comment by 0xd4d** [comment] 2018-04-09 16:28
Dupe of #768

And for the last sentence, see #46

**Closed by 0xd4d** 2018-04-09 16:28 UTC
