### ISSUE TITLE
Suggestion: Add possibility to analyze where specific item from Enum is used

### ISSUE THREAD

**Issue by Yardanico** [0xd4d/dnSpy#337] opened 2017-01-06 12:08 UTC
For example, enum with values
None = 0
One = 1
Two = 2
Three = 8

We can't analyze where 'Three' is used

**Comment by SlowLogicBoy** [comment] 2017-01-06 12:36
It's really difficult since this enum is with Flags, and release assembly optimizes those enums and just writes an int or other flag type in this case 8 everywhere where YourEnum.Three is used and at this point it would became a guessing game. Ofcourse there are places where it's possible to tell where that Enum was used.

**Comment by TiberiumPY** [comment] 2017-01-06 12:45
@SlowLogicBoy but in decompiled source code there's exactly
Enum.None or Enum.One instead of numbers

**Comment by SlowLogicBoy** [comment] 2017-01-06 13:01
and how does IL look like? because Analyzer depends on IL code.

**Comment by TiberiumPY** [comment] 2017-01-06 13:06
@SlowLogicBoy 
look at valuetype
![image](https://cloud.githubusercontent.com/assets/21169548/21718677/0a2d1a68-d42a-11e6-90ca-447235cda3f5.png)

**Comment by TiberiumPY** [comment] 2017-01-06 13:09
@SlowLogicBoy oh, sorry, wrong!

**Comment by TiberiumPY** [comment] 2017-01-06 13:11
@SlowLogicBoy 
5	0025	ldarg.0
6	0026	ldc.i4.1
7	0027	call	bool '#=qr_Wm0DRRH7qstprbjRw8zOObKNqJ7DEMVY5QARVoyoCRQauwt_mA$YBJKTbKPIQW'::'#=q9XBYPCFkmxDNAcnN7DW$Ig=='(valuetype osu_common.Mods, valuetype osu_common.Mods)
8	002C	brfalse.s	13 (003A) ldarg.0

**Comment by SlowLogicBoy** [comment] 2017-01-06 13:20
Osu nice, love that game. Trying to reverse that part too ^^.

Anyway, as you can see it loads integers, decompiler might know those enums because osu_common.Mods, or something in those methods.

**Comment by TiberiumPY** [comment] 2017-01-06 14:08
@SlowLogicBoy actually I already hacked it. Do you have some telegram, discord, skype, or facebook to talk?
and next  - delete all messages here :)

**Comment by SlowLogicBoy** [comment] 2017-01-06 14:09
I use same nick on osu :) and gitter and discord on which I am offline right now

**Comment by TiberiumPY** [comment] 2017-01-06 14:10
@SlowLogicBoy I'll contact you in osu!

**Comment by 0xd4d** [comment] 2017-12-22 22:16
No upvotes, no PR, and I don't need it -> closing it.

**Closed by 0xd4d** 2017-12-22 22:16 UTC
Labels: feature-request

**Comment by chucklu** [comment] 2019-08-24 08:43
Encounter the same problem.
@Yardanico  The problem is the decompiled source code can not get build. It's not perfect code that we can build through visual studio.

**Comment by chucklu** [comment] 2019-08-24 08:44
替换枚举会出现致命问题，https://github.com/0xd4d/dnSpy/issues/337

**Comment by chucklu** [comment] 2019-08-24 08:49
bool @bool = Options.Get().GetBool(Option.IN_WILD_MODE);
bool bool2 = Options.Get().GetBool(Option.IN_RANKED_PLAY_MODE);
