### ISSUE TITLE
Export to Project progress slow when single assembly loaded without mscorlib

### ISSUE THREAD

**Issue by fireundubh** [0xd4d/dnSpy#972] opened 2018-10-17 16:04 UTC
When you first load an assembly and attempt to Export to Project, export progress is extremely slow and dnSpy becomes extremely slow to respond.

![2018-10-17 08_59_25](https://user-images.githubusercontent.com/1261664/47099916-2bf81b00-d1eb-11e8-8696-376da14da4b2.png)

After canceling out of the Export to Project dialog, mscorlib is loaded, and Export to Project works as normal.

**Comment by 0xd4d** [comment] 2018-10-17 16:05
Possibly related to #971

**Comment by 0xd4d** [comment] 2018-10-17 16:48
Try the latest commit, I think it will fix this too.

**Comment by fireundubh** [comment] 2018-10-17 19:49
> Try the latest commit, I think it will fix this too.

No change to behavior. When I cancel out of the dialog, mscorlib is added to the Assembly Explorer, and then I'm able to export as normal.

**Comment by 0xd4d** [comment] 2018-10-17 20:54
I can't repro it, attach the files here if possible.

**Comment by fireundubh** [comment] 2018-10-18 00:06
1. File > Open... [Assembly-CSharp.dll](https://drive.google.com/file/d/1es8-pq_U-C1ktIrwqYyusUakcaDTnlcw/view?usp=sharing)
2. File > Export to Project...
3. Enter folder path.
4. Click Export.

**Comment by 0xd4d** [comment] 2018-10-18 08:03
I still can't repro it, make sure you're using the latest build. Use release builds and don't debug it.

**Comment by fireundubh** [comment] 2018-10-18 08:37
I am using the latest build, but it wouldn't matter because this has been an issue for a long time.

**Comment by 0xd4d** [comment] 2018-10-22 18:29
> edit: You know what's crazy? I compiled a release build and could not reproduce the issue. The release build was running through the debugger, too.

Closing it since neither you nor I can reproduce it.

**Closed by 0xd4d** 2018-10-22 18:29 UTC
Labels: bug, not reproducible
