### ISSUE TITLE
UX Feature Request: keys to jump to letter in assembly explorer

### ISSUE THREAD

**Issue by iwanPlays** [0xd4d/dnSpy#898] opened 2018-07-31 18:55 UTC
in ilspy you can press "f" while the left sidebar is active and you'll jump to the first visible object (class) that starts with "f". super useful for repeat interactions with big projects.

It'd be cool if in dnspy i could press f while in this view:

![image](https://user-images.githubusercontent.com/25465450/43480591-0b02a9ac-9504-11e8-8b46-469a51554e32.png)

and selection would jump to the first class that starts with f

**Comment by 0xd4d** [comment] 2018-07-31 21:13
This is a dupe of #520

**Closed by 0xd4d** 2018-07-31 21:13 UTC
