### ISSUE TITLE
Unable to Watch variables in dnSpy

### ISSUE THREAD

**Issue by Rahul7488** [0xd4d/dnSpy#117] opened 2016-04-18 17:50 UTC
First of all, I would like to thank you for such a cool tool. I am really awe struck with the debugging feature it provides. It helped me in completing a weekend project sooner than i thought it would be.

While i was debugging another tool using dnSpy , i have noticed that when i mouse over to any variable in debug mode , it does not show its value. I have tried to Add a watch on the local variable in Locals window , but the "Add watch" option is disabled. Looks like there is no way to Add a watch on variables or see the value of a variable or change the value of a variable at run time.

I have gone through some earlier bugs such as #38 #112 #46 etc m, but i could not find any help.

Could you please let me know if this is an issue or am i doing it wrong?

**Comment by 0xd4d** [comment] 2016-04-19 15:06
Dupe of #39, #46

**Closed by 0xd4d** 2016-04-19 15:06 UTC
