### ISSUE TITLE
How to check all the selected/visible exceptions?

### ISSUE THREAD

**Issue by CreateAndInject** [0xd4d/dnSpy#570] opened 2017-10-23 09:43 UTC
There's a function named "Enable All Filtered Exceptions" in dnSpy3.x

But how can I check all the selected/visible exceptions? Just now I can onlyi check it one by one.

**Comment by 0xd4d** [comment] 2017-10-23 09:44
Dupe of #567

**Closed by 0xd4d** 2017-10-23 09:44 UTC
