### ISSUE TITLE
Visual Glitches in the x64 dotnet core build

### ISSUE THREAD

**Issue by MrCSharp22** [0xd4d/dnSpy#1231] opened 2019-08-02 13:13 UTC
- What version did you use?
Version 6.0.5 x64 (.NET Core)

- Write down all steps needed to reproduce this issue. Also attach any needed files.
In the assembly explorer, hovering over the items will cause visual glitches as per the screenshot:
![2019-08-02 23_07_04-Window](https://user-images.githubusercontent.com/8640943/62372520-06ba7a80-b57b-11e9-9abd-6922208e83ec.png)

System is running Windows 10 (May 2019 update) with an AMD Ryzen 7 2700X CPU and Radeon RX 580 Series Graphics.

DPI settings are left on default.

I tried the .Net Framework 4.7.2 build of the same version and was unable to reproduce the issue.

**Comment by 0xd4d** [comment] 2019-08-02 17:55
Looks like this known WPF issue: https://github.com/dotnet/wpf/issues/707

**Comment by 0xd4d** [comment] 2019-08-03 07:48
Closing it as dupe of WPF issue.

**Closed by 0xd4d** 2019-08-03 07:48 UTC

**Comment by MrCSharp22** [comment] 2019-08-03 08:42
Agreed @0xd4d this looks like a duplicate of the issue you mentioned.
Thanks!

**Comment by stevenbrix** [comment] 2019-08-07 18:36
@MrCSharp22 does this bug repro every time you use dnspy?

**Comment by MrCSharp22** [comment] 2019-08-07 21:55
@stevenbrix sadly yeah. Within a few seconds of launching it.
