### ISSUE TITLE
the ability to save dnSpy projects

### ISSUE THREAD

**Issue by MostafaNanticock** [0xd4d/dnSpy#1203] opened 2019-07-15 16:28 UTC
i wish there was an option to save my work to a dnspy project, this would become handy when debugging obfuscated executables that performs self hashing to prevent code modification. when i'm debugging the executable i can rename any class or method as i want and still be able to run the program, until i save the module, then the executable would refuse to load.

**Comment by 0xd4d** [comment] 2019-07-15 19:15
Dupe of https://github.com/0xd4d/dnSpy/issues/266 ?

@HoLLy-HaCKeR wrote an extension too: https://github.com/HoLLy-HaCKeR/dnSpy.Extension.HoLLy

**Comment by 0xd4d** [comment] 2019-07-17 22:40
Closing as dupe

**Closed by 0xd4d** 2019-07-17 22:40 UTC
