### ISSUE TITLE
Errors outside of method preventing compilation of single method

### ISSUE THREAD

**Issue by LoyalVizier** [0xd4d/dnSpy#1049] opened 2019-01-09 01:09 UTC
- Version
v6.0.1 (Windows 64-bit)

[UnityScript.zip](https://github.com/0xd4d/dnSpy/files/2738835/UnityScript.zip)
1. Decompile a large class like Creature or Dungeon
2. Edit a single method and compile

I decompiled the files and when I attempted to edit a single method, errors from the class file that were not in the method prevented it from compiling.

Example:
![method](https://user-images.githubusercontent.com/13771064/50869089-410ec100-1378-11e9-8ab4-6e39485526c6.png)

**Comment by 0xd4d** [comment] 2019-01-09 20:00
What kinds of errors are shown, the pic is too small to read.

**Comment by LoyalVizier** [comment] 2019-01-10 00:19
Sorry about that, my snipping tool was messed up.

![unknown](https://user-images.githubusercontent.com/13771064/50936364-0454cf80-1435-11e9-86b6-b83854ebe318.png)

Here are the errors it is referencing.

![maingcs](https://user-images.githubusercontent.com/13771064/50936959-6c0c1a00-1437-11e9-8dfd-26ead9023863.png)

All of the errors when editing the method come from CompilerGenerated.

![image](https://user-images.githubusercontent.com/13771064/50937795-edb17700-143a-11e9-8638-7fb2555b25a1.png)



I tried to edit the class directly, but it ignored everything past 10009 lines. It stopped coloring it and stopped recognizing errors.

![10009_lines](https://user-images.githubusercontent.com/13771064/50937385-facd6680-1438-11e9-9bf0-274d2cef432e.png)

I thought it might be that I was using 64-bit dnSpy on a 32-bit app, however, the same thing occurs on the 32-bit version.

**Comment by 0xd4d** [comment] 2019-01-12 18:43
Closing it, it's a dupe of https://github.com/0xd4d/dnSpy/issues/165

**Closed by 0xd4d** 2019-01-12 18:43 UTC
Labels: compiler
