### ISSUE TITLE
Missing Mono for Unity 2018.4.4-4.16f1

### ISSUE THREAD

**Issue by TBN-MapleWheels** [0xd4d/dnSpy#1427] opened 2020-03-31 16:40 UTC
Good day,

I need the Mono dll for Unity 2018.4.16f1. After I saw that only up to 2018.4.3 was included in the download, I went to the Unity Mono fork to compile my own, but that repo only supports up to 2018.4.5/mbe.

Is there another way to compile/obtain the 2018.4.16f1 dll for Mono? Thanks for the help.

Regards,

**Comment by 0xd4d** [comment] 2020-03-31 18:28
Duplicate of https://github.com/0xd4d/dnSpy/issues/1392

See the above issue.

**Closed by 0xd4d** 2020-03-31 18:28 UTC
