### ISSUE TITLE
2 Compiler Generated classes once edited IEnumerator and 2x yield break

### ISSUE THREAD

**Issue by PiotrKFtw** [0xd4d/dnSpy#662] opened 2017-12-12 10:55 UTC
Just modified unity IEnumerator and dnSpy generated 2 CompilerGenerated class
Also dnSpy put 2x yield break; at the end
Making the code unable to modify because System.InvalidOperationException is being thrown once i try to modify it. and the game isn't working.
Can you fix it ? i can put screenshot

**Comment by UlyssesWu** [comment] 2017-12-12 11:22
CompilerGenerated class - as the name says - is generated by compiler (when building the game) rather than dnSpy. So I believe the answer to "Can you fix it?" is NO. 

The suggestion, or principle, to modify code:
First, rename member names if they have strange names and will be needed in your code.
Then, always try to write correct code no matter what decompiled code looks like.
After getting errors, remove all red lines as long as you don't need them.

**Comment by 0xd4d** [comment] 2017-12-12 12:09
Possibly a dupe of #648

Upload the original files somewhere and repro steps.

**Comment by 0xd4d** [comment] 2017-12-13 10:02
Retry it with the original files or remove the unused duplicate compiler-generated classes.

**Closed** 2017-12-13 10:01 UTC
Labels: bug
