### ISSUE TITLE
If dnSpy cannot debug it should'nt start the process 

### ISSUE THREAD

**Issue by Symbai** [0xd4d/dnSpy#1492] opened 2020-06-27 05:01 UTC
If Debug -> Start Debugging fails (for example by wrong bitness) the target process still launches in background. Expected behavior is that dnSpy would either abort the start or do some pre-checks before even starting it to see if dnSpy might be able to debug the target at all.

**Comment by 0xd4d** [comment] 2020-06-27 10:13
The ICorDebug API shouldn't start the process if it's not the correct bitness, but it still does. Adding checks in dnSpy to detect it won't happens since it's easy to get wrong and prevent someone from debugging something that can be debugged.

**Comment by Symbai** [comment] 2020-06-27 10:39
Where do I report the issue then?

**Comment by 0xd4d** [comment] 2020-07-23 19:43
Perhaps the dotnet/runtime repo. I'll close this since it's caused by the runtime.

**Closed by 0xd4d** 2020-07-23 19:43 UTC
