### ISSUE TITLE
dnSpy crashed when remove module

### ISSUE THREAD

**Issue by bprg** [0xd4d/dnSpy#57] opened 2015-11-19 17:15 UTC
For reproduce the issue, Open dnSpy remove all module -> close dnSpy -> open a file by Context Menu -> remove the module file from dnSpy, Please see the screenshot, Thanks for this great project.

![screenshot](https://cloud.githubusercontent.com/assets/706507/11278223/d2c44d20-8e9e-11e5-91b8-cda570cbe606.png)

**Comment by 0xd4d** [comment] 2015-11-20 14:22
Good find. I've been getting these exceptions too a couple of times but have been unable to reproduce it.

I did a quick check, it's GetVisibleIndexForNode() that returns an incorrect index. @yck1509 , want to take a look at this?

**Comment by 0xd4d** [comment] 2015-11-20 14:33
BTW, all it takes is to open dnSpy with one file in the assembly list and then remove the file. GetVisibleIndexForNode() returns 2 (cached value) instead of 1.

**Comment by 0xd4d** [comment] 2015-11-20 14:36
An update to that, make sure the assembly node is expanded so the module is shown or it won't trigger this bug. Then remove the assembly.

**Comment by yck1509** [comment] 2015-11-20 16:32
Should be fixed by 87d1618139fbe27d26524fb056c35389da81dad3.

**Closed** 2015-11-21 18:09 UTC
