### ISSUE TITLE
About dynamic 

### ISSUE THREAD

**Issue by escms** [0xd4d/dnSpy#742] opened 2018-02-24 15:20 UTC
MVC Source Code:
`base.ViewBag.Url = url;`
because
base.ViewBag is dynamic type,
so ,expect
`((dynamic) base.ViewBag).Url = url;`

dnspy:

`if (UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7 == null)
					{
						UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7 = CallSite<Func<CallSite, object, string, object>>.Create(Binder.SetMember(CSharpBinderFlags.None, "Url", typeof(UserCenterController), new CSharpArgumentInfo[]
						{
							CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.None, null),
							CSharpArgumentInfo.Create(CSharpArgumentInfoFlags.UseCompileTimeType, null)
						}));
					}
					UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7.Target(UserCenterController.<PartialPing>o__SiteContainer6.<>p__Site7, base.ViewBag, arg);`

**Comment by 0xd4d** [comment] 2018-02-24 17:16
Dupe of  #498

**Closed by 0xd4d** 2018-02-24 17:16 UTC
Labels: decompiler
