### ISSUE TITLE
ArgumentNullException when debugging

### ISSUE THREAD

**Issue by sdasda7777** [0xd4d/dnSpy#1221] opened 2019-07-25 11:13 UTC
Older versions just plain crashed, fortunately, lasest version (6.0.5) prints the error.
When loading Dll, and then pressing Debug > Start Debugging, picking application and confirming through "OK", application throws this error (only approximation, since I have to translate to english from my language):

"System.ArgumentNullException: Value cannot be NULL.
Parameter name: runtime
  in
dnSpy.Contracts.Debugger.DbgMessageAsyncProgramMessageEventArgs..ctor(AsyncProgramMessageSource source, String message, DbgRuntime runtime) in"

etc.
Sorry, I could not write it all, uploaded screenshot instead. Hope it helps. I hope it is not just my fault, but all files referenced are dnSpy files, so I guess it's not me.

![image](https://user-images.githubusercontent.com/17746796/61870093-842c1e00-aedd-11e9-8876-037df7a27f6e.png)

**Comment by 0xd4d** [comment] 2019-07-25 15:09
When that message box pops up, you can just hit Ctrl+C to copy the text.

How do I reproduce this? What file did you try to debug? Is it a Unity or a .NET Framework/Core app?

**Comment by sdasda7777** [comment] 2019-07-25 15:13
I have mostly written all steps to reproduction.
I tried debugging Assembly-CSharp.dll, running through Clone Hero Alpha 0.22.5.
Not sure about the last question, but it technically is made in unity.

**Comment by 0xd4d** [comment] 2019-07-25 18:01
I can't reproduce this. Can you copy and paste the log messages in the output window?

**Comment by sdasda7777** [comment] 2019-07-25 18:10
No problem, but some parts are czech.

---------------------------
dnSpy
---------------------------
System.ArgumentNullException: Hodnota nemůže být NULL.

Název parametru: runtime

   v dnSpy.Contracts.Debugger.DbgMessageAsyncProgramMessageEventArgs..ctor(AsyncProgramMessageSource source, String message, DbgRuntime runtime) v C:\projects\dnspy\dnSpy\dnSpy.Contracts.Debugger\DbgMessageEventArgs.cs:řádek 792

   v dnSpy.Debugger.Impl.DbgManagerImpl.OnAsyncProgramMessage_DbgThread(DbgEngine engine, DbgMessageAsyncProgramMessage e) v C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Impl\DbgManagerImpl.cs:řádek 789

   v dnSpy.Debugger.Shared.Dispatcher.RunCallbacks() v C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Shared\Dispatcher.cs:řádek 146

   v dnSpy.Debugger.Shared.Dispatcher.Run() v C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Shared\Dispatcher.cs:řádek 130

   v dnSpy.Debugger.Impl.DebuggerThread.DebuggerThreadProc(AutoResetEvent autoResetEvent) v C:\projects\dnspy\Extensions\dnSpy.Debugger\dnSpy.Debugger\Impl\DebuggerThread.cs:řádek 62

   v System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   v System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   v System.Threading.ThreadHelper.ThreadStart()
---------------------------
OK   
---------------------------

**Comment by 0xd4d** [comment] 2019-07-25 18:13
That's not the Output window.

`Debug -> Windows -> Output`

or

`Alt+2`

**Comment by sdasda7777** [comment] 2019-07-25 18:16
No output there.

**Comment by 0xd4d** [comment] 2019-07-25 18:17
OK, so dnSpy gets the output message before it's connected to the debugged process for some reason.

**Comment by 0xd4d** [comment] 2019-07-25 18:19
How do you debug this, do you start `Assembly-CSharp.dll` or do you start `Clone Hero.exe`?

**Comment by sdasda7777** [comment] 2019-07-25 18:20
I'm not sure what you mean.
I select Assembly-CSharp.dll, click Debug >Start Debugging and select Clone Hero.exe

**Comment by 0xd4d** [comment] 2019-07-25 21:26
Should be fixed in master, but since I can't repro it I can't test it.

A workaround should be: uncheck `Debug -> Options -> Redirect GUI ...`

**Closed by 0xd4d** 2019-07-25 21:26 UTC

**Comment by 0xd4d** [comment] 2019-07-25 22:49
BTW, you should just select the unity game exe and press F5 and it will select the correct debug engine "Unity". You chose ".NET Framework" which is wrong.
