### ISSUE TITLE
Adding code comments

### ISSUE THREAD

**Issue by atomicwrangler** [0xd4d/dnSpy#636] opened 2017-11-30 14:12 UTC
One important thing in static analysis known from software like IDA Pro is adding own comments. There are assemblies that are obfuscated and even when using de4dot it's still not really understandable what it does. It would be nice if there was a feature to add own comments. I would personally write an extension for it but I don't know where to start. What I would need is a syntax tree like this: 

https://github.com/dotnet/roslyn/wiki/Getting-Started-C%23-Syntax-Analysis

or an access to the editor so I can parse it myself and replace content of the viewer.

Is that possible using extensions?

Expected features:
- Add and remove comments
- Save to and load comments from files
- Possibility to add comments from extensions (could be useful in specific cases)

**Comment by atomicwrangler** [comment] 2017-11-30 14:23
Also it would be nice if we would be able to edit names (without modifying original assembly) only for analysis and it would be saved then to a file with extension like `.dndb`.

**Comment by 0xd4d** [comment] 2017-11-30 14:57
Dupe of #266

**Closed by 0xd4d** 2017-11-30 14:57 UTC
Labels: duplicate

**Comment by tfrist** [comment] 2020-03-11 01:12
I have the same request.  Is it already allowed to put in the analyst comments?
