### ISSUE TITLE
Crash upon reloading assemblies

### ISSUE THREAD

**Issue by yck1509** [0xd4d/dnSpy#82] opened 2016-02-03 18:58 UTC
If "Reload All Assemblies" in "File" menu is used. dnSpy crashed with an InvalidOperationException:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at dnSpy.AsmEditor.UndoRedo.DnSpyFileUndoableDocumentsProvider.GetDocumentFile(IDnSpyFile file) in E:\Project\dnSpy\AsmEditor\UndoRedo\DnSpyFileUndoableDocumentsProvider.cs:line 106
   at dnSpy.AsmEditor.UndoRedo.DnSpyFileUndoableDocumentsProvider.dnSpy.AsmEditor.UndoRedo.IUndoableDocumentsProvider.GetUndoObject(Object obj) in E:\Project\dnSpy\AsmEditor\UndoRedo\DnSpyFileUndoableDocumentsProvider.cs:line 71
   at dnSpy.AsmEditor.UndoRedo.UndoCommandManager.GetUndoObject(Object obj) in E:\Project\dnSpy\AsmEditor\UndoRedo\UndoCommandManager.cs:line 416
   at dnSpy.AsmEditor.SaveModule.SaveModuleCommand.GetDocuments(IFileTreeNodeData[] nodes) in E:\Project\dnSpy\AsmEditor\SaveModule\SaveModuleCommand.cs:line 109
   at dnSpy.AsmEditor.SaveModule.SaveModuleCommand.IsEnabled(AsmEditorContext context) in E:\Project\dnSpy\AsmEditor\SaveModule\SaveModuleCommand.cs:line 137
   at dnSpy.Shared.Menus.MenuItemBase`1.dnSpy.Contracts.Menus.IMenuItem.IsEnabled(IMenuItemContext context) in E:\Project\dnSpy\dnSpy.Shared\Menus\MenuItemBase.cs:line 72
   at dnSpy.Menus.MenuManager.<>c__DisplayClass11.<Create>b__f(Object a) in E:\Project\dnSpy\dnSpy\Menus\MenuManager.cs:line 373
   at dnSpy.Shared.MVVM.RelayCommand.CanExecute(Object parameter) in E:\Project\dnSpy\dnSpy.Shared\MVVM\RelayCommand.cs:line 34
   at MS.Internal.Commands.CommandHelpers.CanExecuteCommandSource(ICommandSource commandSource)
   at System.Windows.Controls.MenuItem.UpdateCanExecute()
   at System.Windows.Controls.MenuItem.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.Input.CanExecuteChangedEventManager.HandlerSink.OnCanExecuteChanged(Object sender, EventArgs e)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RequerySuggestedEventManager.OnRequerySuggested(Object sender, EventArgs args)
   at System.Windows.Input.CommandManager.RaiseRequerySuggested(Object obj)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by 0xd4d** [comment] 2016-02-03 19:24
It's not something I'm able to reproduce. Could you show me the files you have in your FileList section in dnSpy.xml?

**Comment by RetiredQQ** [comment] 2016-02-04 08:32
![4](https://cloud.githubusercontent.com/assets/13232132/12809794/d994bcac-cb5c-11e5-9859-dca541443c09.PNG)

I also get this error after saving module and close it the error appear.

**Comment by 0xd4d** [comment] 2016-02-04 08:40
Could you explain exactly what you did?

1. Remove dnSpy.xml
2. Start dnSpy
3. ???

**Comment by 0xd4d** [comment] 2016-02-04 09:02
Fix works for me. Re-open if you still see that message box.

**Closed** 2016-02-04 09:01 UTC
