### ISSUE TITLE
Generates <>f__(...) variables and $'s

### ISSUE THREAD

**Issue by LightniX** [0xd4d/dnSpy#1113] opened 2019-04-09 08:34 UTC
VERSION: 6.0.4

I'm not sure if this is really an issue
The decompiler generates variables starting with'<>f__'

Example:
Following is inside a class named: 'Param'
```
Dictionary<string, Action<int>> status_function_dic = new Dictionary<string, Action<int>>();
status_function_dic.Add("level", delegate(int add_num)
{
Param <>f__this = this;
<>f__this.status_.class_bonus_status.lvl = <>f__this.status_.class_bonus_status.lvl + add_num;
});
```
  The '<>' causes an error. Could I remove the definition and replace '<>f__this' with 'this'?
`Param.<>f__switch$map1A = new Dictionary<string, int>(2)`
  The '<>', '$' seem to cause an error and '<>f__switch$map1A' isn't defined anywhere

These <> and $ are the only errors in the code but they are causing thousands of errors.
How can i fix these? What are they? Why do they appear?

**Comment by 0xd4d** [comment] 2019-04-09 13:13
This is a dupe of https://github.com/0xd4d/dnSpy/issues/694 , it has a couple of regexes you can use.

**Closed by 0xd4d** 2019-04-09 13:13 UTC
